config/routes.rb
Rails.application.routes.draw do
  resources :courses do
    resources :lessons, except: [:index, :show], controller: "courses/lessons"
    member do
      patch :generate_lessons
    end
  end
  resources :subjects
  resources :classrooms
  devise_for :users, controllers: { 
    confirmations: 'users/confirmations', 
    omniauth_callbacks: 'users/omniauth_callbacks', 
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :show, :destroy, :edit, :update] do
    member do
      patch :ban
      patch :resend_confirmation_instructions
      patch :resend_invitation
    end
  end

  root 'static_pages#landing_page'

  get 'calendar', to: 'static_pages#calendar'

  get '/About', to: 'static_pages#privacy_policy', as: :about
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:landing_page, :privacy_policy]
  
  def landing_page
  end

  def privacy_policy
  end

  def calendar
    @users = User.all.order(email: :asc)
    @classrooms = Classroom.all.order(name: :asc)
    @courses = Course.all.order(id: :asc)

    if params.has_key?(:user_id)
      lessons = Lesson.includes(:user, :classroom, :course, :attendances)
      if params[:user_id].present?
        lessons = lessons.where(user_id: params[:user_id])
      end
      if params[:classroom_id].present?
        lessons = lessons.where(classroom_id: params[:classroom_id])
      end
      if params[:course_id].present?
        lessons = lessons.where(course_id: params[:course_id])
      end
      @lessons = lessons.all
    else
      @lessons = Lesson.includes(:user, :classroom, :course, :attendances)
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_calendar.html.erb
<div class="card shadow">
  <div class="card-body">
    <div class="table-responsive">
    <%= month_calendar(events: @lessons, attribute: :start) do |date, lessons| %>
      <%= date %>
      
      <ul class="list-group">
        <% lessons.each do |lesson| %>
        <li class="list-group-item">
        
          Lesson:
          <%= link_to lesson.id, edit_course_lesson_path(lesson.course, lesson) %>
         <% unless @course.present? %>
            Course:
            <%= link_to lesson.course_id, course_path(lesson.course) %>
          <% end %>
          Instructor:
          <%= link_to lesson.user, user_path(lesson.user) %>
          <br/>
          <span> Projected $<%= lesson.teacher_price_start_cents %></span> /
          <span> $<%= lesson.teacher_price_final_cents %></span>
          <br/>
          Classroom:
          <%= link_to lesson.classroom, classroom_path(lesson.classroom)  %>
          Status: 
          <%= status_label(lesson.status) %>
          <br/>
          Lesson Time: 
          <%= lesson.course.start_time&.strftime("%I:%M %p") %>
          

          <ul class="list-group">
            <% lesson.attendances.each do |attendance| %>
              <li class="list-group-item">
                <%= link_to attendance.user, user_path(attendance.user) %>
                <%= status_label(attendance.status) %>
                <span> $<%= attendance.student_price_start_cents %></span> /
                <span> $<%= attendance.student_price_final_cents %></span>
                </li>
            <% end %>
          </ul>
          
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  </div>
</div>
<br/>

app/views/static_pages/calendar.html.erb
<br>
<%= form_tag calendar_path, method: :get do %>
    <% unless params.has_key?(:user_id) %>
     <%= select_tag :user_id, options_for_select(@users.map{|x| [x.to_s, x.id]}), {prompt: "Select Instructor", onchange: "this.form.submit()"} %>
     <%= select_tag :classroom_id, options_for_select(@classrooms.map{|x| [x.to_s, x.id]}), {prompt: "Select Classroom", onchange: "this.form.submit()"} %>
     <%= select_tag :course_id, options_for_select(@courses.map{|x| [x.to_s, x.id]}), {prompt: "Select Course", onchange: "this.form.submit()"} %>
    <% else %>
     <%= select_tag :user_id, options_for_select(@users.map{|x| [x.to_s, x.id]}, params[:user_id]), {prompt: "Select Instructor", onchange: "this.form.submit()"} %>
     <%= select_tag :Classroom_id, options_for_select(@classrooms.map{|x| [x.to_s, x.id]}, params[:classroom_id]), {prompt: "Select Classroom", onchange: "this.form.submit()"} %>
     <%= select_tag :Course_id, options_for_select(@courses.map{|x| [x.to_s, x.id]}, params[:course_id]), {prompt: "Select Course", onchange: "this.form.submit()"} %>
    <%= link_to "Refresh", calendar_path, class: "btn btn-sm btn-secondary" %>    
     <% end %>
<% end %> 
<br/>



<%= render 'static_pages/calendar' %>

app/views/static_pages/landing_page.html.erb
<div class="text-center">
    <h1> Agenda </h1>
    <h3> Ruby on Rails 6</h3>
</div>

<div class="text-center">
<% unless user_signed_in? %>
  <hr>
  <% User.omniauth_providers.each do |provider| %>
    <%= link_to omniauth_authorize_path(User, provider), method: :post, class: "btn btn-md btn-outline-primary", data: { disable_with: "Connecting..." } do %>
      Sign in with 
      <%= provider.capitalize %> 
    <% end %> 
  <% end %>
<% end %>
</div>
<hr>


<div class="text-center">
  <h2>Core features:</h2>
</div>

<div class="container list-unstyled ">
  <div class="row align-items-start">
    <div class="col-md-6">
        <div class="text-center">
            <h2>
            Authentication
            </h2>
        </div>
        <ul class="list-group list-unstyled text-center ">
            <li>
                Devise email authorization
            </li>
            <li>
                Log in with Google
            </li>
            <li>
                Log in with Github
            </li>
            <li>
                Invisible Recaptcha
            </li>
            <li>
                Email address confirmations
            </li>
        </ul>
    </div>

        <div class="col-md-6">
            <div class="text-center">
                <h2>Authorization</h2>
            </div>
            <ul class="list-group list-unstyled text-center">
                <li>
                    User roles
                </li>
                <li>
                    Admin Privalges (edit/ban/update)
                </li>
            </ul>
        </div>

    </div>
</div>

app/views/static_pages/privacy_policy.html.erb
<div class="container text-center">
    <h1>Welcome to the Agenda App</h1>
    <hr/>
    <p>The project was created with Ruby on Rails 6</p>
    <p>Log in with your social accounts</p>
    <p>Create Subjects to teach or be apart of</p>
    <p>Update your attendance on the calander</p>
    <p>Track the money you spend or make from the courses</p>
</div>