config/routes.rb
Rails.application.routes.draw do
  resources :courses do
    resources :lessons, except: [:index, :show], controller: "courses/lessons"
    member do
      patch :generate_lessons
    end
  end
  resources :subjects
  resources :classrooms
  devise_for :users, controllers: { 
    confirmations: 'users/confirmations', 
    omniauth_callbacks: 'users/omniauth_callbacks', 
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :show, :destroy, :edit, :update] do
    member do
      patch :ban
      patch :resend_confirmation_instructions
      patch :resend_invitation
    end
  end

  root 'static_pages#landing_page'

  get 'calendar', to: 'static_pages#calendar'

  get '/About', to: 'static_pages#privacy_policy', as: :about
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable, :trackable, :lockable, :invitable, 
         :omniauthable, omniauth_providers: [:github, :google_oauth2]

include Roleable


    def self.from_omniauth(access_token)
      data = access_token.info
      user = User.find_by(email: data['email'].downcase)
      unless user
           user = User.create(
              email: data['email'],
              password: Devise.friendly_token[0,20]
           )
       end
       user.provider = access_token.provider
       user.uid = access_token.uid
       unless user.name.present?
        user.name = data.name
       end
       user.image = data.image
       user.save

       user.confirmed_at = Time.now
       user
    end

    after_create do
      # assign default role to user
      self.update(student: true)
    end

    has_many :enrollments, dependent: :restrict_with_error
    has_many :lessons, dependent: :restrict_with_error
    has_many :attendances, dependent: :restrict_with_error
    has_many :courses, dependent: :restrict_with_error

    
    after_touch do
      calculate_student_total
      calculate_teacher_total
      calculate_balance
    end
   
    monetize :student_total, as: :student_total_cents
    monetize :teacher_price_total, as: :teacher_price_total_cents
    monetize :balance, as: :balance_cents

    def to_s
      email
    end

    def to_label
      to_s
    end

    private
     
    def calculate_student_total
      update_column :student_total, attendances.map(&:student_price_final).sum
    end

    def calculate_teacher_total
      update_column :teacher_price_total, lessons.map(&:teacher_price_final).sum
    end

    def calculate_balance
      update_column :balance, (teacher_price_total - student_total)
    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
    private
    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource) # In case you want to sign in the user
      user_path(resource)
    end
  end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    
 def github
    handle_auth "Github"
 end


 def google_oauth2
    handle_auth "Google"
 end
  
  def handle_auth(kind)
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env['omniauth.auth'])
        if @user.persisted?
  
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: kind
          sign_in_and_redirect @user, event: :authentication
        else
    
          session['devise.handle_auth_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
        end
    end
    
  end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  invisible_captcha only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :require_admin, only: [:ban, :destroy, :resend_confirmation_instructions]
 before_action :require_admin_or_inviter, only: [:resend_invitation]
 before_action :require_admin_teacher_or_owner, only: [:edit, :update]
    def index
        @users = User.all.order(created_at: :asc)
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        if @user.update(user_params)
            redirect_to @user, notice: "User was successfully updated."
        else
            render :edit
        end
    end
      
    def show
        @user = User.find(params[:id])
    end

    def resend_confirmation_instructions
        @user = User.find(params[:id])
        if @user.confirmed? == false && @user.created_by_invite? == false
            @user.resend_confirmation_instructions
            redirect_to @user, notice: "Confirmation Instructions were resent"
        else
            redirect_to @user, notice: "Confirmation Instructions were resent"
        end
    end

    def resend_invitation
        @user = User.find(params[:id])
        if @user.created_by_invite? && @user.invitation_accepted? == false && @user.confirmed? == false
        @user.invite!
            redirect_to @user, notice: "Invitation has been resent"
        else
            redirect_to @user, notice: "The User has already been confirmed"
        end
    end
      

    def destroy
        @user = User.find(params[:id])
       if @user.destroy
        redirect_to users_path, notice: "User was successfully destroyed."
       else
        redirect_to users_path, alert: "User has associations. Can not be destroyed."
       end
    end

    def ban
        @user = User.find(params[:id])
        if @user == current_user
            redirect_to @user, alert: "You cannot ban yourself!"
        else
            if @user.access_locked?
            @user.unlock_access!
            else
                @user.lock_access!
            end
            redirect_to @user, notice: "User access locked: #{@user.access_locked?}"
        end
    end


    private 

        def user_params
            list_allowed_params = []
            list_allowed_params += [:name] if current_user == @user || current_user.admin? || current_user.teacher?
            list_allowed_params += [*User::ROLES] if current_user.admin?
            params.require(:user).permit(list_allowed_params)
            # params.require(:user).permit(*User::ROLES, :name)
        end

        def require_admin
            unless current_user.admin? || current_user.teacher?
                redirect_to (request.referrer || root_path), alert: "You are not authorized to perform this action"
            end
        end

        def require_admin_or_inviter
            @user = User.find(params[:id])
            unless current_user.admin? || @user.invited_by == current_user
                redirect_to (request.referrer || root_path), alert: "You are not authorized to perform this aciton"
            end
        end

        def require_admin_teacher_or_owner
            @user = User.find(params[:id])
            unless current_user.admin? || current_user.teacher? || current_user == @user
                redirect_to (request.referrer || root_path), alert: "You are not authorized to perform this aciton"
            end
        end
end

app/helpers/users_helper.rb
module UsersHelper

    def ban_status(user)
        if user.access_locked?
            "Unban"
        else
            "Ban"
        end

    end

end

app/views/users/_user.html.erb
<b>Id:</b>
<%= link_to user.id, user_path(user)%><br/>
<b>Email:</b>
<%= user.email %><br />
<b>Confirmation:</b>
<%= boolean_label(user.confirmed?) %>
<br/>
<b><%= "sign_in_count".humanize %>: </b>
<%= user.sign_in_count %>
<br/>
<b><%= "current_sign_in_at".humanize %>: </b>
<%= user.current_sign_in_at %>
<br/>
<b><%= "last_sign_in_at".humanize %>: </b>
<%= user.last_sign_in_at %>
<br/>
<b><%= "current_sign_in_ip".humanize %>: </b>
<%= user.current_sign_in_ip %>
<br/>
<b><%= "last_sign_in_ip".humanize %>: </b>
<%= user.last_sign_in_ip %>
<br/>
<b><%= "locked_at".humanize %>: </b>
<%= user.locked_at %>
<br/>
<b><%= "provider".humanize %>: </b>
<%= user.provider %>
<br/>
<b><%= "uid".humanize %>: </b>
<%= user.uid %>
<br/>
<b><%= "name".humanize %>: </b>
<%= user.name %>
<br/>
<b><%= "image".humanize %>: </b>
<% if user.image.present? %>
<%= image_tag user.image, size: "50x50" %>
<% end %>
<br/>
<b><%= "roles".humanize %>: </b>
<%= user.active_roles.join(", ") %>
<br/>
<% if current_user.admin? || current_user.teacher? %>
    <%= link_to "Edit roles", edit_user_path(user), class: "btn btn-sm btn-secondary" %>
    <%= link_to ban_status(user), ban_user_path(user), method: :patch, class: "btn btn-sm btn-warning" %>
    <%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %>
<% end %>

app/views/users/edit.html.erb
<div class="card shadow">
  <div class="card-header">
    <h2> Editing Roles for <%= @user.name %> </h2>
  </div>
  <div class="card-body">
    <%= form_for(@user) do |f| %>
    
        <% if @user.errors.any? %>
            <div id="error_explanation">
            <h2>
                <%= pluralize(@user.errors.count, "error") %>
                prohibited this user from being saved:
            </h2>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li>
                    <%= message %>
                    </li>
                <% end %>
            </ul>
            </div>
        <% end %>

        <%= f.label :name %>
        <%= f.text_field :name %>
        <br/>

        <% if current_user.admin? || current_user.teacher? %>
            <% User::ROLES.each do |role| %>
                <label>
                    <%= f.check_box role %>
                    <%= role.to_s.humanize %>
                </label>
                <br>
            <% end %>
        <% end %>    
        <br/>
        <%= f.button "Submit", type: "submit", class: "btn btn-primary" %>
        <% end %>
  </div>

  <div class="card-footer">
        <br/>
        <%= link_to "Cancel", user_path(@user), class:"btn btn-sm btn-secondary" %>
  </div>  
</div>






 

app/views/users/index.html.erb
<h3>
  <div class="text-center">
    Users
    <div class="badge badge-info">
      <%= @users.count %>
    </div>
    <%= link_to "Send Invite", new_user_invitation_path, class: 'btn btn-primary' %>
  </div>
</h3>

<div class="table-responsive" >
    <table class="table table-dark table-striped table-hover shadow">
        <thead>
            <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Confirmed</th>
            <th>Banned?</th>
            <th>Name</th>
            <th>Image</th>
            <th>Roles</th>
            <th>Invitation accepted?</th>
            <th> Actions</th>
            <th colspan="8">Notifications</th>
            </tr>
        </thead>

        <tbody class="table-group-divider">
            <% @users.each do |user| %>
                <tr>
                    <td><%= link_to user.id, user_path(user)%><br/></td>
                    <td><%= user%> </td>
                    <td>
                    <%= boolean_label(user.confirmed?) %> 
                    </td>
                    <td><%= boolean_label(user.access_locked?) %> </td>
                    <td>
                        <% if user.name.present? %>
                            <%= user.name %> 
                        <% else %>
                            <%= link_to "Enter Name", edit_user_path(user), class:"btn btn-sm btn-secondary" %>
                        <% end %>
                    </td>
                    <td> 
                        <% if user.image.present? %>
                            <%= image_tag user.image, size: "30x30" %>
                        <% end %>
                    </td>
                    <td><%= user.active_roles.join(', ') %> </td>
                    <td>
                    <%= boolean_label(user.invitation_accepted?) %>   
                    </td>
                    <td>
                            <%= link_to "Edit", edit_user_path(user), class: "btn btn-sm btn-secondary"%>
                            <%= link_to ban_status(user), ban_user_path(user), method: :patch, class: "btn btn-sm btn-warning" %>
                            <%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger"  %>
                    </td>
                    <td>
                    <% if current_user.admin? || user.invited_by == current_user %>
                        <%  if user.created_by_invite? && user.invitation_accepted? == false && user.confirmed? == false %>
                            <%= link_to "Resend Invitation", resend_invitation_user_path(user), method: :patch %>
                        <% end %> 
                    <% end %> 
                    <% if user.confirmed? == false && user.created_by_invite? == false %>
                        <%= link_to "Resend confirmation Instructions", resend_confirmation_instructions_user_path(user), method: :patch %>
                    <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/users/show.html.erb
<div class='card shadow'>
    <div class="card-body">
        <b>Id:</b>
        <%= @user.id %><br/>
        <b>Email:</b>
        <%= @user.email %><br />
        <b>Confirmation:</b>
        <%= boolean_label(@user.confirmed?) %>
        <br/>
        <b>Created by Invitation:</b>
        <%= boolean_label(@user.created_by_invite?) %>
        <br/>
        <b><%= "sign_in_count".humanize %>: </b>
        <%= @user.sign_in_count %>
        <br/>
        <b><%= "current_sign_in".humanize %>: </b>
        <%= @user.current_sign_in_at&.strftime("%b/%d/%y - %I:%M %p") %>
        <br/>
        <b><%= "last_sign_in".humanize %>: </b>
        <%= @user.last_sign_in_at&.strftime("%b/%d/%y - %I:%M %p") %>
        <br/>
        <b><%= "current_sign_in_ip".humanize %>: </b>
        <%= @user.current_sign_in_ip %>
        <br/>
        <b><%= "last_sign_in_ip".humanize %>: </b>
        <%= @user.last_sign_in_ip %>
        <br/>
        <b><%= "locked_at".humanize %>: </b>
        <%= @user.locked_at %>
        <br/>
        <b><%= "provider".humanize %>: </b>
        <%= @user.provider %>
        <br/>
        <b><%= "uid".humanize %>: </b>
        <%= @user.uid %>
        <br/>
        <b><%= "name".humanize %>: </b>
        <%= @user.name %>
        <br/>
        <b><%= "image".humanize %>: </b>
        <% if @user.image.present? %>
        <%= image_tag @user.image, size: "50x50" %>
        <% end %>
        <br/>
        <b><%= "Invited by".humanize %>: </b>
        <% if @user.invited_by %>
            <%= @user.invited_by %>
            <% else %>
            none
        <% end %>
        <br/>
        <b><%= "roles".humanize %>: </b>
        <%= @user.active_roles.join(", ") %>
        <br/>
        
            <%= link_to "Edit", edit_user_path(@user), class: "btn btn-sm btn-secondary" %>
            <%= link_to ban_status(@user), ban_user_path(@user), method: :patch, class: "btn btn-sm btn-warning" %>
            <%= link_to "Delete", @user, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %>
        
    </div>


        <br/>
    <div class="card-footer">
        <b><%= "Attendances_Count".humanize %>: </b>
        <%= @user.attendances.count %>
        <br/>
        <b><%= "Total Student Cost".humanize %>: </b>
        <span> $<%= @user.student_total_cents %></span>
        <br/>
        <b><%= "Lessons_count".humanize %>: </b>
        <%= @user.lessons.count %>
        <br/>
        <b><%= "Total Teacher Earnings".humanize %>: </b>
        <span> $<%= @user.teacher_price_total_cents %></span>
        <br/>
        <b><%= "Balance".humanize %>: </b>
        <span> $<%= @user.balance_cents %></span>
    </div>
    <div class="card-footer">
        <%= link_to "All Users", users_path, class: "btn btn-sm btn-secondary" %>
    </div>
</div>