config/routes.rb
Rails.application.routes.draw do
  resources :courses do
    resources :lessons, except: [:index, :show], controller: "courses/lessons"
    member do
      patch :generate_lessons
    end
  end
  resources :subjects
  resources :classrooms
  devise_for :users, controllers: { 
    confirmations: 'users/confirmations', 
    omniauth_callbacks: 'users/omniauth_callbacks', 
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :show, :destroy, :edit, :update] do
    member do
      patch :ban
      patch :resend_confirmation_instructions
      patch :resend_invitation
    end
  end

  root 'static_pages#landing_page'

  get 'calendar', to: 'static_pages#calendar'

  get '/About', to: 'static_pages#privacy_policy', as: :about
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user, touch: true
  belongs_to :classroom
  belongs_to :course
  has_many :attendances, inverse_of: :lesson, dependent: :destroy
  accepts_nested_attributes_for :attendances, reject_if: :all_blank, allow_destroy: true

  validates :status, :start, presence: true

  
  STATUSES = [:planned, :confirmed, :cancelled]
  
  def self.statuses
    STATUSES.map { |status| [status, status]}
  end
  
  monetize :teacher_price_start, as: :teacher_price_start_cents
  monetize :teacher_price_final, as: :teacher_price_final_cents

    after_create do
      update_column :teacher_price_start, course.subject.teacher_price
      
    end

  after_save do
      if status == "planned"
          update_column :teacher_price_final, 0
      elsif status == "confirmed"
          update_column :teacher_price_final, teacher_price_start
      elsif status == "cancelled"
          update_column :teacher_price_final, 0
      end
  end

end

app/controllers/courses/lessons_controller.rb
class Courses::LessonsController < ApplicationController
  before_action :set_course
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]


  def new
    @lesson = Lesson.new(classroom_id: @course.classroom_id, user_id: @course.user_id, start: @course.start_time)
    @lesson.attendances.build(@course.enrollments.as_json(only: [:user_id]))
  end

 
  def edit
  end


  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.course = @course

    if @lesson.save
      redirect_to @course, notice: "Lesson was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    
      if @lesson.update(lesson_params)
        redirect_to @course, notice: "Lesson was successfully updated."
      else
        render :edit
      end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy
    redirect_to @course, notice: "Lesson was successfully destroyed."
  end

  private
   
    def set_course
      @course = Course.find(params[:course_id])
    end

    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:user_id, :classroom_id, :course_id, :status, :start, 
      attendances_attributes: [:id, :user_id, :status, :_destroy])
    end
end

app/views/lessons/_attendance_fields.html.erb
<div class="attendance_fields">
  <%= form.association :user %>
  <%= form.input :status, collection: Attendance.statuses, as: :radio_buttons, :item_wrapper_class => 'inline', include_blank: false %>
 
  <%= link_to_remove_nested(form) do %>
    <p class="btn btn-link">
      Remove Attendance
    </p>
    <% end %>
</div>

app/views/lessons/_calendar.html.erb
<div class="card shadow">
  <div class="card-body">
    <div class="table-responsive">
    <%= month_calendar(events: @lessons, attribute: :start) do |date, lessons| %>
      <%= date %>
      <% lessons.each do |lesson| %>
        <div>
          Id:
          <%= link_to lesson.id, lesson_path(lesson) %>
          Course:
          <%= link_to lesson.course_id, course_path(lesson.course) %>
          User:
          <%= link_to lesson.user_id, user_path(lesson.user) %>
          Classroom:
          <%= link_to lesson.classroom_id, classroom_path(lesson.classroom)  %>
          Status: 
          <%= status_label(lesson.status) %>
          Start: 
          <%= lesson.start.strftime("%I:%M %p") %>
          <br/>
          <% lesson.attendances.each do |attendance| %>
            <%= attendance.user %>
            <%= status_label(attendance.status) %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  </div>
</div>
<br/>

app/views/lessons/_form.html.erb
<%= simple_form_for(@lesson) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :classroom %>
    <%= f.association :course %>
    <%= f.input :status, as: :radio_buttons, collection: Lesson.statuses, :item_wrapper_class => 'inline', include_blank: false %>
    <%= f.input :start, ampm: true, minute_step: 15, start_year: Date.today.year, end_year: Date.today.year + 1 %>

    <h3>Attendance</h3>  
    <%= link_to_add_nested(f, :attendances, '#attendances') do %>
      <p class="btn btn-link">Add Attendance</p>
    <% end %>

    <div id='attendances'>
      <%= f.simple_fields_for :attendances do |attendance| %>
        <%= render 'attendance_fields', form: attendance %>
      <% end %>
    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      Edit
      Lesson
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', lesson: @lesson %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', @lesson %>
    <%= link_to 'Cancel', lessons_path %>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="card shadow">
  <div class="card-header">
    <h4>
      New
      Lesson
    </h4>
  </div>
  <div class="card-body">
    <%= render 'form', lesson: @lesson %>
  </div>
  <div class="card-footer">
    <%= link_to 'Cancel', lessons_path %>
  </div>
</div>