config/routes.rb
Rails.application.routes.draw do
  resources :courses do
    resources :lessons, except: [:index, :show], controller: "courses/lessons"
    member do
      patch :generate_lessons
    end
  end
  resources :subjects
  resources :classrooms
  devise_for :users, controllers: { 
    confirmations: 'users/confirmations', 
    omniauth_callbacks: 'users/omniauth_callbacks', 
    registrations: 'users/registrations'
  }

  resources :users, only: [:index, :show, :destroy, :edit, :update] do
    member do
      patch :ban
      patch :resend_confirmation_instructions
      patch :resend_invitation
    end
  end

  root 'static_pages#landing_page'

  get 'calendar', to: 'static_pages#calendar'

  get '/About', to: 'static_pages#privacy_policy', as: :about
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand">
     Agenda
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= link_to root_path, class: "nav-link #{'active fw-bold' if current_page?(root_path)}" do %>
          <div class="fa fa-home"></div>
          Home
        <% end %>
        <% if current_user %>
          <%= link_to users_path, class: "nav-link #{'active fw-bold' if current_page?(users_path)}" do %>
            <div class="fa fa-users"></div>
            Users
          <% end %>
          <%= link_to classrooms_path, class: "nav-link  #{'active fw-bold' if current_page?(classrooms_path)}" do %>
          <div class="fa-solid fa-door-open"></div>
            Classrooms
          <% end %>
          <%= link_to subjects_path, class: "nav-link #{'active fw-bold' if current_page?(subjects_path)}" do %>
            <div class="fa-solid fa-book-open"></div>
            Subjects
          <% end %>
          <%= link_to courses_path, class: "nav-link #{'active fw-bold' if current_page?(courses_path)}" do %>
            <div class="fa-solid fa-graduation-cap"></div>
            Courses
          <% end %>
          <%= link_to new_user_invitation_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_invitation_path)}" do %>
          <div class="fa-solid fa-envelope"></div>
            Invite Users
          <% end %>
          <%= link_to calendar_path, class: "nav-link #{'active fw-bold' if current_page?(calendar_path)}" do %>
          <div class="fa fa-calendar-alt"></div>
            Calendar
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="fa fa-user"></div>
              <b><%= current_user.email %></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to user_path(current_user), class: "dropdown-item #{'active fw-bold' if current_page?(user_path(current_user))}" do %>
                <div class="fa fa-user"></div>
                <b>My Profile</b>
              <% end %>
              <%= link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do %>
              <div class="fa fa-cog"></div>
              <b>Account settings</b>
            <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <div class="fa fa-sign-out-alt"></div>
                <b>Sign out</b>
              <% end %>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_session_path)}" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_registration_path)}" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
   <script type="text/javascript">
      <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
   	 toastr['<%= type %>']('<%= f[1] %>', '', {"closeButton": true, "positionClass": "toast-top-center", "timeOut": 4000});
   <% end %>
   </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascript %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <%= render 'layouts/messages' %>
    <div class="container-fluid" >
      <br />
      <%= yield %>
    </div> 
  </body>
  <footer class="bg-dark text-light"> 
    <div class="container text-center pb-2 pt-2">   
      <%= link_to "About", about_path %>
      <p/>
    </div>
    </footer>
</html>